dist: trusty
language: java
sudo: false
jdk:
  - openjdk10
install: "/bin/true"
script:
  - mvn clean install -q -B
deploy:
  - skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) -t